# Generated by Django 5.2 on 2025-04-10 18:45

import annex.models.annex6a
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annex_type', models.CharField(blank=True, editable=False, max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('inventory_no', models.CharField(max_length=50)),
                ('applicator_no', models.CharField(max_length=50)),
                ('leoni_terminal_no', models.CharField(max_length=50)),
                ('supplier_terminal_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'annex',
            },
        ),
        migrations.CreateModel(
            name='Annex6a',
            fields=[
                ('annex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='annex.annex')),
                ('terminal_no', models.CharField(max_length=50)),
                ('applicator_supplier', models.CharField(max_length=100)),
                ('drawing_revision', models.CharField(max_length=50)),
                ('original_zwg', models.BooleanField(default=False)),
                ('cable_type_supplier', models.CharField(max_length=50)),
                ('cross_sectio', models.CharField(max_length=50)),
                ('terminal_supplier', models.CharField(max_length=50)),
                ('wire_type', models.CharField(max_length=50)),
                ('leoni_wire_no', models.CharField(max_length=50)),
                ('sws_supplier', models.CharField(max_length=100)),
                ('vw_sws_no', models.CharField(max_length=50)),
                ('leoni_sws_no', models.CharField(max_length=50)),
                ('critical_part', models.BooleanField(default=False)),
                ('intervention', models.BooleanField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('first_off_release', models.BooleanField(blank=True, null=True)),
                ('original_ch', models.FloatField(blank=True, null=True)),
                ('original_ch_plus', models.FloatField(blank=True, null=True)),
                ('original_cw', models.FloatField(blank=True, null=True)),
                ('original_cw_plus', models.FloatField(blank=True, null=True)),
                ('original_ich', models.FloatField(blank=True, null=True)),
                ('original_ich_plus', models.FloatField(blank=True, null=True)),
                ('original_icw', models.FloatField(blank=True, null=True)),
                ('original_icw_plus', models.FloatField(blank=True, null=True)),
                ('measured_ch', models.FloatField(blank=True, null=True)),
                ('measured_cw', models.FloatField(blank=True, null=True)),
                ('measured_ich', models.FloatField(blank=True, null=True)),
                ('measured_icw', models.FloatField(blank=True, null=True)),
                ('s', models.BooleanField(default=False)),
                ('n', models.BooleanField(default=False)),
                ('vw', models.BooleanField(default=False)),
                ('sg', models.BooleanField(default=False)),
                ('ch_should', models.FloatField(blank=True, null=True)),
                ('ch_is', models.FloatField(blank=True, null=True)),
                ('pull_force_ability_should', models.FloatField(blank=True, null=True)),
                ('pull_force_ability_is', models.FloatField(blank=True, null=True)),
                ('pull_force_should', models.FloatField(blank=True, null=True)),
                ('pull_force_is', models.FloatField(blank=True, null=True)),
                ('aw_should', models.FloatField(blank=True, null=True)),
                ('aw_is', models.FloatField(blank=True, null=True)),
                ('la_should', models.FloatField(blank=True, null=True)),
                ('la_is', models.FloatField(blank=True, null=True)),
                ('fa_should', models.FloatField(blank=True, null=True)),
                ('fa_is', models.FloatField(blank=True, null=True)),
                ('cfe_should', models.FloatField(blank=True, null=True)),
                ('cfe_is', models.FloatField(blank=True, null=True)),
                ('gh_should', models.FloatField(blank=True, null=True)),
                ('gh_is', models.FloatField(blank=True, null=True)),
                ('gb_should', models.FloatField(blank=True, null=True)),
                ('gb_is', models.FloatField(blank=True, null=True)),
                ('sb_should', models.FloatField(blank=True, null=True)),
                ('sb_is', models.FloatField(blank=True, null=True)),
                ('standard_1', models.BooleanField(default=False)),
                ('standard_2', models.BooleanField(default=False)),
                ('standard_3', models.BooleanField(default=False)),
                ('standard_4', models.BooleanField(default=False)),
                ('standard_5', models.BooleanField(default=False)),
                ('standard_6', models.BooleanField(default=False)),
                ('micrograph_release', models.BooleanField(default=False)),
                ('qm_release', models.BooleanField(default=False)),
                ('remarks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='List of remarks', size=None)),
                ('image_field', models.ImageField(blank=True, null=True, upload_to=annex.models.annex6a.annex_6a_image_upload)),
            ],
            options={
                'db_table': 'annex6a',
            },
            bases=('annex.annex',),
        ),
    ]
